In [1]:
import pandas as pd
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [4]:
house_prices=pd.read_csv(r'house_prices_dataset.csv')
house_prices.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,year_built,year_renovated,zipcode,lat,long,price
0,3,1,2803,1153,1,0,0,3,9,2003,0,98001,47.660671,-121.785347,835016.23
1,5,3,783,9762,1,0,2,4,4,2019,0,98003,47.681937,-122.151515,326073.09
2,3,3,3412,2842,2,0,3,4,9,1961,1962,98002,47.182798,-121.792089,1025404.09
3,2,3,2222,9020,2,1,2,4,4,2008,1962,98004,47.440995,-121.871224,758764.79
4,4,1,4713,1584,2,0,3,4,5,1987,0,98005,47.701306,-122.416623,1314784.23

In [6]:
house_prices.columns

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'year_built',
       'year_renovated', 'zipcode', 'lat', 'long', 'price'],
      dtype='object')

In [8]:
house_prices=house_prices.drop(columns=['zipcode', 'lat', 'long'], axis=1)
house_prices.head()

KeyError: "['zipcode', 'lat', 'long'] not found in axis"

In [9]:
house_prices.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,year_built,year_renovated,price
0,3,1,2803,1153,1,0,0,3,9,2003,0,835016.23
1,5,3,783,9762,1,0,2,4,4,2019,0,326073.09
2,3,3,3412,2842,2,0,3,4,9,1961,1962,1025404.09
3,2,3,2222,9020,2,1,2,4,4,2008,1962,758764.79
4,4,1,4713,1584,2,0,3,4,5,1987,0,1314784.23

In [10]:
house_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bedrooms        1000 non-null   int64
 1   bathrooms       1000 non-null   int64
 2   sqft_living     1000 non-null   int64
 3   sqft_lot        1000 non-null   int64
 4   floors          1000 non-null   int64
 5   waterfront      1000 non-null   int64
 6   view            1000 non-null   int64
 7   condition       1000 non-null   int64
 8   grade           1000 non-null   int64
 9   year_built      1000 non-null   int64
 10  year_renovated  1000 non-null   int64
 11  price           1000 non-null   float64
dtypes: float64(1), int64(11)
memory usage: 93.9 KB

In [11]:
house_prices['condition'].value_counts()

condition
5    216
2    207
4    199
1    190
3    188
Name: count, dtype: int64

In [12]:
house_prices['view'].value_counts()

view
1    265
0    259
3    250
2    226
Name: count, dtype: int64

In [13]:
house_prices['waterfront'].value_counts()

waterfront
0    893
1    107
Name: count, dtype: int64

In [14]:
house_prices['grade'].value_counts()

grade
12    111
1      95
3      91
10     90
8      86
4      85
5      80
9      80
6      76
11     75
7      72
2      59
Name: count, dtype: int64

In [15]:
house_prices['floors'].value_counts()

floors
2    501
1    499
Name: count, dtype: int64

In [17]:
house_prices['bedrooms'].value_counts()

bedrooms
4    224
2    206
1    203
5    188
3    179
Name: count, dtype: int64

In [18]:
house_prices.columns

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'year_built',
       'year_renovated', 'price'],
      dtype='object')

In [19]:
formula="price~ bedrooms+bathrooms+sqft_living+sqft_lot+floors+year_built+year_renovated+C(waterfront)+C(view)+C(condition)+C(grade)"
lm=ols(formula=formula,data=house_prices).fit()
table=sm.stats.anova_lm(lm,typ=2)
print(table)

                      sum_sq     df              F         PR(>F)
C(waterfront)   9.166195e+11    1.0    2424.099877  2.058608e-266
C(view)         1.776019e+10    3.0      15.656251   5.974182e-10
C(condition)    2.041546e+11    4.0     134.977239   9.551189e-92
C(grade)        7.624866e+11   11.0     183.316235  2.858685e-228
bedrooms        4.708068e+11    1.0    1245.099809  2.690992e-176
bathrooms       6.161723e+10    1.0     162.953472   1.290603e-34
sqft_living     1.015938e+14    1.0  268675.916515   0.000000e+00
sqft_lot        1.959280e+09    1.0       5.181529   2.304476e-02
floors          4.142126e+07    1.0       0.109543   7.407363e-01
year_built      5.214565e+06    1.0       0.013790   9.065413e-01
year_renovated  1.077184e+08    1.0       0.284873   5.936468e-01
Residual        3.679183e+11  973.0            NaN            NaN